export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const FETCH_GAMES_REQUEST = 'FETCH_GAMES_REQUEST';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAILURE = 'FETCH_GAMES_FAILURE';

export const FETCH_TOP_RATING_GAMES_REQUEST = 'FETCH_TOP_RATING_GAMES_REQUEST';
export const FETCH_TOP_RATING_GAMES_SUCCESS = 'FETCH_TOP_RATING_GAMES_SUCCESS';
export const FETCH_TOP_RATING_GAMES_FAILURE = 'FETCH_TOP_RATING_GAMES_FAILURE';
